"""Re-export i18n utilities for shared/ modules.

The canonical i18n data lives in i18n_backend.py (auto-generated by
scripts/generate_i18n.py from shared/i18n.json). This module re-exports
so shared/*.py can use relative imports.
"""

import sys, os

# Ensure project root is on path for direct import
_project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _project_root not in sys.path:
    sys.path.insert(0, _project_root)

from i18n_backend import t, get_lang, TRANSLATIONS  # noqa: F401, E402
